##### Core behavior #####
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g default-terminal "tmux-256color"
set -g focus-events on
set -g mouse on
setw -g mode-keys vi
set -sg escape-time 10

##### Colors #####
set -g terminal-overrides ",*:Tc"
set -g status-style bg=default
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

##### UX #####
set -g bell-action none
set -g status-interval 5
set -g history-limit 50000
set -g detach-on-destroy off

##### Windows & panes #####
setw -g automatic-rename on
set -g renumber-windows on
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

##### Copy/paste #####
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

